### ISSUE TITLE
Support for Recurring Tasks

### ISSUE THREAD

**Issue by adib-progresif** [mikestefanello/backlite#2]
I have been using backlite for one of my projects and it works fine when it comes to having a certain task run at a specified time. However, what if I wanted a task to be run daily or monthly at a specific time? As of now I have to add the task in an infinite for loop at daily intervals using sleep which is not recommended.  

```go
go func() {
   for {
      c.Tasks.Add(tasks.RenewWalletTransactionBalanceTask{}).Ctx(ctx).Save()

      now := time.Now()
      nextMidnight := time.Date(now.Year(), now.Month(), now.Day()+1, 0, 0, 0, 0, loc)
      sleepDuration := nextMidnight.Sub(now)

      time.Sleep(sleepDuration)
   }
}()
``` 

Is there a better way to do this? Or will there be an upcoming feature in Backlite for Recurring Tasks? 

Thanks

**Comment by mikestefanello** [comment]
A few options come to mind:

1. Have your task processor callback create the next task at the very end of processing but set the date of the task to the time you want it executed. You can extract your backlite client from the provided context by calling `FromContext(ctx)`. This avoids the need for a separate goroutine and loop, etc, and it will continue to recreate itself forever. The challenge is how to handle creating the very first task and never creating it again manually.
2. Use a cron library such as [this](https://github.com/robfig/cron). That makes it a bit easier to execute _something_ at every midnight.
3. What you're already doing. I don't think there's a problem with this.

I don't plan have a plan to add recurring tasks but that could change.

**Comment by adib-progresif** [comment]
Thank you for sharing, I am able to work with your suggestions.
